services:
  runtime:
    build:
      context: .
      dockerfile: ./docker/runtime/Dockerfile
    command: sleep infinity
    container_name: runtime
    tty: true
    working_dir: /app
    volumes:
      - ./:/app
